export const userInformation = [
    {name: "Nguyen Nhat Thien",age: 19 ,address: "Nghe An Province", description: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.", img:"https://res.cloudinary.com/chuoi2taps/image/upload/v1654925757/images/Ellipse1_2x_usyqf8.png"}
];
export const recentPost =[
    {id: 1, name: "Making a design system from scratch", date: "12 Feb 2020", tag:"Design, Pattern", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet."},
    {id: 2, name: "Creating pixel perfect icons in Figma", date: "12 Feb 2020", tag:"Figma, Icon Design", description: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet."},
];
export const featureWork = [
    {id:1, name: "Designing Dashboards", year: 2020, cate: "Dashboards", description: "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.", img:"https://res.cloudinary.com/chuoi2taps/image/upload/v1654925759/images/Rectangle30_oxjpli.png"},
    {id:2, name: "Vibrant Portraits of 2020", year: 2018, cate: "Illustration", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.", img:"https://res.cloudinary.com/chuoi2taps/image/upload/v1654925761/images/Rectangle32_fnv38e.png"},
    {id:3, name: "36 Days of Malayalam type", year: 2018, cate:"Typography", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.",img:"https://res.cloudinary.com/chuoi2taps/image/upload/v1654925762/images/Rectangle34_li8wrl.png"},
    {id:4, name:"Components", year: 2018, cate:"Component, Design", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.", img:"https://res.cloudinary.com/chuoi2taps/image/upload/v1654925763/images/Rectangle40_xam6cy.png"},
];
export const blogPost = [
    {id:1,name: "UI Interactions of the day", date: "12 Feb 2019", tag: "Express, Handlebars", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet."},
    {id:2,name: "UI Interactions of the week", date: "12 Feb 2019", tag: "Express, Handlebars", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet."},
    {id:3,name: "UI Interactions of the month", date: "12 Feb 2019", tag: "Express, Handlebars", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet."},
    {id:4,name: "UI Interactions of the year", date: "12 Feb 2019", tag: "Express, Handlebars", description:"Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet."},
]